
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"ben-pscourses","number":32,"title":"BUG fix: Deleting a personal schedule doesn't delete associated PSCourses","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/32"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-coursesPage","number":29,"title":"Add more descriptive personal course page","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/29"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-button","number":27,"title":"More descriptive error message + button without stryker files","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/27"}]
