
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yera-desc","number":26,"title":"Created new branch without all of the stryker files finishing course description ","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/26"},{"author":{"id":"U_kgDOBXv56g","is_bot":false,"login":"sophiattran","name":""},"headRefName":"Sophia-UpdateCoursesForRangeOfQuarters","number":22,"title":"FEATURE: Added frontend for job to update courses by range of quarters","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/22"},{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"ben-made-img-home-button","number":20,"title":"FEATURE: made storke tower a home button","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/20"},{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"ben-add-dev-info","number":19,"title":"FEATURE: Add link to developer/GH info in Admin dropdown","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/19"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-PSCourse-stories","number":17,"title":"Created missing stories for PSCourse Pages","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/17"}]
