
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdYtJA","is_bot":false,"login":"bwr02","name":"Ben Richardson"},"headRefName":"ben-course-level-bug-fix","number":18,"title":"Ben course level bug fix","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/18"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-PSCourse-stories","number":17,"title":"Created missing stories for PSCourse Pages","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/17"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"point","number":13,"title":"Removed unnecessary exclamation point","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-3/pull/13"}]
